---
title: "Alex's Code"
author: "Alex Mix"
date: "12/5/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggcorrplot)
library(tidyverse)
library(GGally)
library(dplyr)
library(fpc)
library(cluster)

```


```{r}
coaster_data <- read.csv("FileName.csv")
#Reorder Rating variable
coaster_data <- coaster_data %>% mutate(Rating = recode_factor(Rating, '10 (Superior)'="10.0 (Superior)"))

order <- c("2.0 (Horrible)", "3.0 (Bad)", "3.5 (Bad)", "4.0 (Below Average)", "5.0 (Average)", "5.5 (Average)", "6.0 (Above Average)", "6.5 (Above Average)", "7.0 (Good)", "7.5 (Good)", "8.0 (Great)", "8.5 (Great)", "9.0 (Excellent)", "9.5 (Excellent)", "10.0 (Superior)")

coaster_data$Rating <- factor(coaster_data$Rating, levels = order)

coaster_data<-coaster_data %>% separate(Rating, c("Score.2","Cat_score"), " ")
coaster_data$Score.2 <- as.double(coaster_data$Score.2)
```


```{r}
# data exploration
pairs <- pairs(coaster_data[,c(5,6,7,8,9,10,11,14)])
#pairs

corr_matrix <- model.matrix(~0+., data=coaster_data[,c(14,8,9,10,11)]) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag = F, type="lower", lab=TRUE, lab_size=2, title = "Correlation Matrix")
#corr_matrix

#the plot zone
ggplot( data= coaster_data, aes(x=height.x, y=speed.x, color=Rating)) + geom_point()
ggplot( data= coaster_data, aes(x=length.x, y=speed.x, color=Rating)) + geom_point()
ggplot( data= coaster_data, aes(x=num_inversions, y=speed.x, color=score)) + geom_point()
ggplot( data= coaster_data, aes(x=score, y=speed.x, color=material_type)) + geom_point()
ggplot( data= coaster_data, aes(x=height.x, y=speed.x, color=num_inversions)) + geom_point()

biggg <- ggpairs(coaster_data[,c(8,9,10,11,14)])
#biggg
```


```{r}
coaster_data_cat <- coaster_data %>% mutate(Factor.material = case_when(material_type == "Steel" ~ 0,
                                                                     TRUE ~ 1))
coaster_data_cat <- coaster_data_cat %>% mutate(Factor.seating = case_when(seating_type == "Sit Down" ~ 0,
                                                                     TRUE ~ 1))
coaster_data_cat <- coaster_data_cat %>% mutate(Factor.launch = case_when(launch == "Chain lift hill" ~ 0,
                                                                     TRUE ~ 1))
coaster_data_cat <- coaster_data_cat %>% mutate(Factor.restraint = case_when(restraint == "Lap bar" ~ 0,
                                                                     restraint == "Common lap bar" ~ 0,
                                                                     TRUE~ 1))
coaster_data_cat <- coaster_data_cat[,c(4,9:12,15, 18:21)]

# coaster_data_cat$Factor.material <- as.factor(coaster_data_cat$Factor.material)
# coaster_data_cat$Factor.seating <- as.factor(coaster_data_cat$Factor.seating)
# coaster_data_cat$Factor.launch <- as.factor(coaster_data_cat$Factor.launch)
# coaster_data_cat$Factor.restraint <- as.factor(coaster_data_cat$Factor.restraint)

#coaster_data_cat[,1:6] <- scale(coaster_data_cat[,1:6])
```


```{r}
coaster_data$launch <- str_trim(coaster_data$launch)
#kmeans clustering
coasters.k2 <- kmeans(coasters_scaled, centers=2, iter.max = 200, nstart = 50)
coasters.k2  

coasters.k3 <- kmeans(scale(coaster_data_cat[,1:6]), centers=3, iter.max = 200, nstart = 50)
coasters.k3  #46.9%

coasters.k4 <- kmeans(coasters_scaled, centers=4, iter.max = 200, nstart = 50)
coasters.k4  #56.1

coasters.k5 <- kmeans(coasters_scaled, centers=5, iter.max = 200, nstart = 50)
coasters.k5  #65.3%

coasters.k6 <- kmeans(coasters_scaled, centers=6, iter.max = 200, nstart = 50)
coasters.k6  #70.9%

coasters.k7 <- kmeans(coasters_scaled, centers=7, iter.max = 200, nstart = 50)
coasters.k7  #75.1%

clusplot(coasters_scaled, coasters.k2$cluster, color=TRUE, shade=TRUE, lines=0)
clusplot(coaster_data_cat[,1:6], coasters.k3$cluster, color=TRUE, shade=TRUE, lines=0)
clusplot(coasters_scaled, coasters.k4$cluster, color=TRUE, shade=TRUE, lines=0)
clusplot(coasters_scaled, coasters.k5$cluster, color=TRUE, shade=TRUE, labels=2, lines=0)
clusplot(coasters_scaled, coasters.k6$cluster, color=TRUE, shade=TRUE, labels=2, lines=0)
clusplot(coasters_scaled, coasters.k7$cluster, color=TRUE, shade=TRUE, labels=2, lines=0)

plotcluster(coasters_scaled, coasters.k7$cluster)
```

```{r}
# samples within cluster 1
c1 <-coaster_data_cat[which(coasters.k3$cluster == 1),]
c1 <- c1 %>% mutate(cluster =1)
# samples within cluster 2
c2 <-coaster_data_cat[which(coasters.k3$cluster == 2),]
c2 <- c2 %>% mutate(cluster =2)
#samples within cluster 3
c3 <-coaster_data_cat[which(coasters.k3$cluster == 3),]
c3 <- c3 %>% mutate(cluster =3)
```

```{r}
c12 <- rbind(c1, c2)
c123 <- rbind(c12,c3)
```

```{r}
x1 <- with(c123, c123[cluster== 1,-11])
x2 <- with(c123, c123[cluster==2, -11])
x3 <- with(c123, c123[cluster==3, -11])
m1 <- round(apply(x1, 2, mean),2)
m2 <- round(apply(x2, 2, mean),2)
m3 <- round(apply(x3, 2, mean),2)
meh<-rbind(m1,m2)
meh <- rbind(meh,m3)
meh <- as.data.frame(meh)
meh <- rename(meh, Speed = speed.x)
meh <- rename(meh, Height = height.x)
meh <- rename(meh, Length = length.x)
meh <- rename(meh, Inversions = num_inversions)
meh <- rename(meh, Score.1 = score)
meh <- rename(meh, Material = Factor.material)
meh <- rename(meh, Seating = Factor.seating)
meh <- rename(meh, Launch = Factor.launch)
meh <- rename(meh, Restraint = Factor.restraint)
row.names(meh) <- c("Cluster 1 Means", "Cluster 2 Means", "Cluster 3 Means")
meh<-meh[,c(2,3,4,5,6,1,7,8,9,10)]
formattable::formattable(meh)
```

```{r}
m1 <- round(apply(x1, 2, sd),2)
m2 <- round(apply(x2, 2, sd),2)
m3 <- round(apply(x3, 2, sd),2)
meh<-rbind(m1,m2)
meh <- rbind(meh,m3)
meh <- as.data.frame(meh)
meh <- rename(meh, Speed = speed.x)
meh <- rename(meh, Height = height.x)
meh <- rename(meh, Length = length.x)
meh <- rename(meh, Inversions = num_inversions)
meh <- rename(meh, Score.1 = score)
meh <- rename(meh, Material = Factor.material)
meh <- rename(meh, Seating = Factor.seating)
meh <- rename(meh, Launch = Factor.launch)
meh <- rename(meh, Restraint = Factor.restraint)
row.names(meh) <- c("Cluster 1 SD", "Cluster 2 SD", "Cluster 3 SD")
meh<-meh[,c(2,3,4,5,6,1,7,8,9,10)]
formattable::formattable(meh)
```


```{r}
 clusplot(coaster_data_cat[,1:6], coasters.k3$cluster, color=TRUE, shade=TRUE, labels=5, lines=0, col.clus = c("dark red", "dark blue", "dark green"), col.p = "black", main = "Three Clusters of Kmeans")
```

